version: "3"
services:
  broker:
    image: eclipse-mosquitto
    volumes:
      - "./mosquitto:/mosquitto"
    ports:
      - "1883:1883"
  node-red:
    depends_on:
      - broker
    image: nodered/node-red:latest
    volumes:
      - "./node-red:/data"
    user: "0"
    ports:
      - "1880:1880"
  database:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD='password'
      - MYSQL_DATABASE='TimeSeries'
      - MYSQL_USER='user'
      - MYSQL_PASSWORD='password'
    working_dir: /app
    volumes:
      - .:/app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8083:80
    environment:
      - PMA_HOST=database
    depends_on:
      - database
networks:
  default:
    external:
        name: iot-network
